In [1]:
import statistics

In [3]:
num = [1,2,3]
statistics.mean(num)

2

In [5]:
from statistics import mean
mean(num)

2

In [6]:
import numpy as np

In [7]:
list1 = [1, 2, 3, 4, 5]

In [9]:
x = np.array(list1)

In [10]:
type(x)

numpy.ndarray

In [12]:
np.shape(x)

(5,)

In [14]:
x.shape

(5,)

In [15]:
np.array([2, 2, 2, 2])

array([2, 2, 2, 2])

In [16]:
np.array((3, 3, 3, 3))

array([3, 3, 3, 3])

In [18]:
np.array({1, 2, 3}).shape

()

In [19]:
array2d = np.array([[1,1,1], [2,2,2], [3,3,3]])

In [23]:
array2d

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [24]:
array2d.shape

(3, 3)

In [25]:
list1 = [1, 2, 3, 4]
list2 = [2, 3, 4, 5]

In [27]:
arr2d_2 = np.array([list1, list2])

In [28]:
arr2d_2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [29]:
arr2d_2.shape

(2, 4)

In [30]:
100/3

33.333333333333336

In [31]:
np.longdouble(100)/ np.longdouble(3)

33.333333333333333332

In [36]:
np.array([1, 2,3.1453,5],dtype=np.longdouble)

array([1.    , 2.    , 3.1453, 5.    ], dtype=float128)

In [73]:
arr1 = np.array([1, 1, 1, 1])
arr2 = np.array([[11,21, 31, 41, 51, 61]])

In [42]:
arr1.shape

(4,)

In [54]:
arr2.shape

(1, 4)

In [74]:
arr2[0][::5]

array([11, 61])

In [77]:
array_1 = np.array([1,2,3,4,5,6,4,2,2,1])

In [78]:
array_2 = np.array([[2,3,2,4,6], [5,6,3,2,4]])

In [79]:
array_1.shape

(10,)

In [81]:
array_2.shape

(2, 5)

In [85]:
reshape_array1 = np.reshape(array_1,(2, 5))

In [87]:
reshape_array1

array([[1, 2, 3, 4, 5],
       [6, 4, 2, 2, 1]])

In [95]:
array_2

array([[2, 3, 2, 4, 6],
       [5, 6, 3, 2, 4]])

In [90]:
np.ndarray.flatten(array_2).shape

(10,)

In [98]:
np.ravel(array_2).shape

(10,)

In [99]:
new_array_1 = np.array([[1,1,1],[2,2,2]])

In [101]:
new_array_2 = np.array([[3,3,3], [4,4,4], [5,5,5]])

In [102]:
new_array_3 = np.array([[3, 3],[4,4],[5,5]])

In [104]:
np.concatenate((new_array_1, new_array_2), axis=0)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [105]:
new_array_1.shape

(2, 3)

In [106]:
new_array_2.shape

(3, 3)

In [107]:
new_array_3.shape

(3, 2)

In [108]:
new_array_1

array([[1, 1, 1],
       [2, 2, 2]])

In [109]:
np.transpose(new_array_1)

array([[1, 2],
       [1, 2],
       [1, 2]])

In [111]:
new_array_2.transpose()

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [112]:
array_unsort = np.array([[1, 10, 3], [2, 3, 1]])

In [113]:
array_unsort

array([[ 1, 10,  3],
       [ 2,  3,  1]])

In [114]:
np.sort(array_unsort)

array([[ 1,  3, 10],
       [ 1,  2,  3]])

In [116]:
np.sort(array_unsort, axis=0)

array([[ 1,  3,  1],
       [ 2, 10,  3]])

In [117]:
np.full((2,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [131]:
np.full((2,2), 5)

array([[5, 5],
       [5, 5]])

In [139]:
np.random.randint(-20,20,(3,3))

array([[ 16,  -3,   9],
       [-10, -16,  -7],
       [  1,  14,  10]])

In [142]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [146]:
np.identity(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [147]:
np.identity(10, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [148]:
add_a_1 = np.array([[1,2,3,3,3]])

In [154]:
add_a_2 = np.array([1,2,3,4,5,5,3,2,4,2,1,2,3,4,5]).reshape(5,3)

In [156]:
add_a_3 = np.array([1,2,3,4,5,5,3,2,4,2,1,2,3,4,5]).reshape(3,5)

In [158]:
add_a_1.shape

(1, 5)

In [159]:
add_a_2.shape

(5, 3)

In [160]:
add_a_3.shape

(3, 5)

In [161]:
add_a_1 + add_a_1

array([[2, 4, 6, 6, 6]])

In [163]:
add_a_2 + add_a_3

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 